# Recipe for build and integration testing on Travis-CI

dist: bionic
language: cpp

# If we set 'ccache: true', Travis installs replacement ccache wrappers of system compilers, which we don't want,
# so we'll do our own ccache management.
# Note the heuristics for whether cache is shared or distinct:
# https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices
cache:
  pip: true
  directories:
    # Note: if a cache store forks due to a stage with parallel jobs that Travis identifies as part of the same flow,
    # we must make sure that the parallel jobs do not write to any of the same caches. Also note that all stages use the
    # same cache, so early stage jobs may see caches from later stages from previous builds in the same branch.
    - $HOME/.ccache_gromacs
    - $HOME/.ccache_py
# Allows us to build and install GROMACS in one CI stage, then use the installation in a subsequent stage
#    - $HOME/install

compiler: gcc

env:
  - PY=3.6
  - PY=3.7
  - PY=3.8

addons:
  apt:
    packages:
    - doxygen
    - libblas-dev
    - libcr-dev
    - libfftw3-dev
    - liblapack-dev
    - libmpich-dev
    - libxml2-dev
    - mpich

# Set up for all jobs
before_install:
  - pyenv versions
  # get exactly one Python version: the last listed patch version for the selected minor version
  - pyenv whence python${PY} && export PY_VER=`pyenv whence python${PY} | tail -1`
  - pyenv shell $PY_VER && pyenv shell
#  - python-config --includes
  - pyenv prefix ${PY_VER} && export PYTHON_PREFIX=`pyenv prefix ${PY_VER}`
  - pyenv which python && export PYTHON=`pyenv which python`
  - source ./ci_scripts/set_compilers

install:
  - export CCACHE_DIR=$HOME/.ccache_gromacs
  - ccache -s
  - ./ci_scripts/install_gromacs_2020.sh
# Need to update infrastructure for new CMake version requirements to build against devel.
#  - if [ "${TRAVIS_BRANCH}" != "master" ] ; then ./ci_scripts/install_gromacs_devel.sh ; fi

before_script:
  - export CCACHE_DIR=$HOME/.ccache_py
  - ccache -s
  - $PYTHON -m pip install --upgrade pip setuptools
  - $PYTHON -m pip install --upgrade packaging scikit-build
  - $PYTHON -m pip install --no-cache-dir --upgrade --no-binary ":all:" --force-reinstall networkx mpi4py MarkupSafe
  - $PYTHON -m pip install pytest numpy networkx sphinx sphinx_rtd_theme

script:
  - source $HOME/install/gromacs_2020/bin/GMXRC && $PYTHON -m pip install gmxapi
  - ./ci_scripts/sample_restraint.sh
# Need to update infrastructure for new CMake version requirements to build against devel.
#  - |
#    if [ "${TRAVIS_BRANCH}" != master ] ; then
#      source $HOME/install/gromacs_devel/bin/GMXRC
#      ./ci_scripts/pygmx_devel.sh
#      ./ci_scripts/sample_restraint.sh
#    fi
